
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: MotionModule
// ---------------------------------------------

#include "MotionModule.h"

static MotionModule *instance = nullptr;

/**
 * @brief Constructor for MotionModule
 *
 */
MotionModule::MotionModule() { instance = this; }

/**
 * @brief Destructor for MotionModule
 *
 */
MotionModule::~MotionModule() {}

/**
 * @brief
 * Inititalize BMA423 sensor
 */
void MotionModule::begin() {}

/**
 * @brief
 * Checks for available interrupts from BMA432 sensor
 */
void MotionModule::update() {}

/**
 * Read steps count from the BMA423 sensor
 * @note this caches the value for 60 seconds before reading from the sensor
 * @return the current steps
 */
uint32_t MotionModule::getCurrentSteps() { return 100; }

/**
 * Callback that is triggered when an interrupt is detected
 */
void MotionModule::irqCallback() {}

/**
 * Set the interrupt callback function
 * @param callback the callback function
 */
void MotionModule::setInterruptCallback(void (*callback)(uint16_t)) {
  interruptCallback = callback;
}

/**
 * Get the interrupt flags as string
 * @param irq the interrupt flags
 * @return interrupt flags string
 */
String MotionModule::getInterrupts(uint16_t irq) {
  String state = "No interrupts";

  return state;
}
