
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: MotionModule
// ---------------------------------------------

#ifndef MOTIONMODULE_H
#define MOTIONMODULE_H

#include <Wire.h>
#include <SensorBMA423.hpp>
#include <Timber.h>

#define SENSOR_IRQ 13

enum BMA423_INTS
{
    STEP_CNTR_INT = (0x02),
    ACTIVITY_INT = (0x04),
    TILT_INT = (0x08),
    WAKEUP_INT = (0x20),
    ANY_NO_MOTION_INT = (0x40),
    ERROR_INT = (0x80),
};

class MotionModule : public SensorBMA423
{
public:
    // accessible from outside the class
    MotionModule();  // constructor
    ~MotionModule(); // destructor

    void begin();
    void update();

    uint32_t getCurrentSteps();

    void setInterruptCallback(void (*callback)(uint16_t));
    String getInterrupts(uint16_t irq);

protected:
    // cannot be accessed from outside the class, however, they can be accessed in inherited classes
private:
    unsigned long lastUpdate;
    uint32_t steps;

    bool irqFlag;
    static void irqCallback();

    void (*interruptCallback)(uint16_t) = nullptr;
};

#endif
